### ISSUE TITLE
'The service "markup_fallback_password_encoder" has a dependency on a non-existent service "security.encoder.blowfish

### ISSUE THREAD

**Issue by tobemedia** [usemarkup/FallbackPasswordEncoderBundle#1]
Please add a installation howto:
- Install with composer
- add to AppKernel.php 
  new Markup\FallbackPasswordEncoderBundle\MarkupFallbackPasswordEncoderBundle(),

I tried it by adding
markup_fallback_password_encoder:
    encoders:
        primary:
            id: security.encoder.blowfish

to config.yml but got the following error:
'The service "markup_fallback_password_encoder" has a dependency on a non-existent service "security.encoder.blowfish

How to access the standard symfony security encoders?

**Comment by shieldo** [comment]
I've added an Installation section to the README - thanks for pointing out that omission!

The bundle does not, at the current time, allow use of the standard Symfony security encoders, as these are not declared as services in the DIC.  I agree that it needs to achieve that, as most people will be using these (this bundle was actually written before the bcrypt encoder was introduced to Symfony 2.2).

**Comment by shieldo** [comment]
btw the "security.encoder.blowfish" name is just an example encoder service name.
